export const db = {
  members: [
    {
      id: 1,
      email: 'demo@example.com',
      password: 'password123',
      nickname: '데모유저',
      isLogin: false,
      createdAt: '2023-01-01T00:00:00Z',
    },
    {
      id: 2,
      email: 'mentor@example.com',
      password: 'password123',
      nickname: '김멘토',
      isLogin: false,
      createdAt: '2023-01-02T00:00:00Z',
    },
    {
      id: 3,
      email: 'mentee@example.com',
      password: 'password123',
      nickname: '이멘티',
      isLogin: false,
      createdAt: '2023-01-03T00:00:00Z',
    },
  ],
  mentors: [
    {
      mentorId: 1,
      memberId: 1,
      mentorName: '데모유저',
      career: '주니어',
      field: '프론트엔드',
      task: '웹 개발',
      email: 'demo@example.com',
      phone: '010-1234-5678',
      aboutMe: '데모 유저입니다. 프론트엔드 개발에 대해 알려드립니다.',
      github: 'https://github.com/demo',
    },
    {
      mentorId: 2,
      memberId: 2,
      mentorName: '김멘토',
      career: '시니어',
      field: '백엔드',
      task: '서버 개발',
      email: 'mentor@example.com',
      phone: '010-8765-4321',
      aboutMe: '안녕하세요, 백엔드 시니어 개발자 김멘토입니다.',
      github: 'https://github.com/mentor',
    },
  ],
  mentees: [
    {
      menteeId: 1,
      memberId: 1,
      mentoringId: 2,
      name: '데모유저',
    },
    {
      menteeId: 2,
      memberId: 3,
      mentoringId: 2,
      name: '이멘티',
    },
  ],
  mentorings: [
    {
      mentoringId: 1,
      mentorId: 1,
      mentorName: '데모유저',
      title: '[데모] React 기초부터 심화까지',
      content: 'React의 기본 개념부터 Hooks, State Management까지 함께 공부합니다.',
      pay: '50,000원',
      period: '4주',
      participants: 5,
      category: '프론트엔드',
      field: '프론트엔드',
      task: '웹 개발',
      career: '주니어',
      aboutMe: '데모 유저입니다. 프론트엔드 개발에 대해 알려드립니다.',
      status: '모집중',
      startDate: '2023-05-01',
      endDate: '2023-05-28',
      thumb: 'https://source.unsplash.com/random/300x200?react',
    },
    {
      mentoringId: 2,
      mentorId: 2,
      mentorName: '김멘토',
      title: 'Spring Boot로 만드는 MSA',
      content: 'Spring Boot와 클라우드 기술을 활용하여 마이크로서비스 아키텍처를 구축합니다.',
      pay: '100,000원',
      period: '8주',
      participants: 10,
      category: '백엔드',
      field: '백엔드',
      task: '서버 개발',
      career: '시니어',
      aboutMe: '안녕하세요, 백엔드 시니어 개발자 김멘토입니다.',
      status: '모집중',
      startDate: '2023-06-01',
      endDate: '2023-07-27',
      thumb: 'https://source.unsplash.com/random/300x200?server',
    },
  ],
  payments: [],
};
