export const mockData = {
  "members": [
    {
      "id": 1,
      "email": "demo@example.com",
      "password": "password123",
      "nickname": "데모유저",
      "isLogin": true,
      "createdAt": "2024-01-01T00:00:00Z"
    }
  ],
  "mentors": [
    {
      "mentorId": 1,
      "memberId": 1,
      "mentorName": "김개발",
      "career": "시니어",
      "field": "백엔드",
      "task": "Spring Boot, MSA, DevOps",
      "email": "kimdev@example.com",
      "phone": "010-1234-5678",
      "aboutMe": "10년차 백엔드 개발자입니다. 스타트업부터 대기업까지 다양한 환경에서 경험을 쌓았습니다.",
      "github": "https://github.com/kimdev",
      "mentoringDtoList": [
        {
          "id": 1,
          "title": "Spring Boot 기초부터 실무까지",
          "content": "Spring Boot를 활용한 RESTful API 개발과 JPA, Security 등 실무에서 필요한 기술을 배웁니다.",
          "pay": "50000",
          "period": "1개월",
          "participants": 5,
          "category": "백엔드"
        },
        {
          "id": 2,
          "title": "MSA 설계 및 구현",
          "content": "마이크로서비스 아키텍처의 개념부터 실제 구현까지 단계별로 학습합니다.",
          "pay": "80000",
          "period": "2개월",
          "participants": 3,
          "category": "아키텍처"
        }
      ]
    },
    {
      "mentorId": 2,
      "memberId": 2,
      "mentorName": "이프론트",
      "career": "미들",
      "field": "프론트엔드",
      "task": "React, TypeScript, Next.js",
      "email": "leefront@example.com",
      "phone": "010-2345-6789",
      "aboutMe": "5년차 프론트엔드 개발자입니다. React와 TypeScript를 주력으로 사용합니다.",
      "github": "https://github.com/leefront",
      "mentoringDtoList": [
        {
          "id": 3,
          "title": "React + TypeScript 완벽 가이드",
          "content": "React와 TypeScript를 함께 사용하여 타입 안정성이 높은 애플리케이션을 개발하는 방법을 배웁니다.",
          "pay": "60000",
          "period": "1.5개월",
          "participants": 4,
          "category": "프론트엔드"
        }
      ]
    },
    {
      "mentorId": 3,
      "memberId": 3,
      "mentorName": "박풀스택",
      "career": "시니어",
      "field": "풀스택",
      "task": "Node.js, React, Docker, AWS",
      "email": "parkfull@example.com",
      "phone": "010-3456-7890",
      "aboutMe": "8년차 풀스택 개발자입니다. 프론트부터 백엔드, 인프라까지 전반적인 멘토링이 가능합니다.",
      "github": "https://github.com/parkfull",
      "mentoringDtoList": [
        {
          "id": 4,
          "title": "풀스택 개발자 되기",
          "content": "프론트엔드부터 백엔드, 배포까지 웹 서비스 개발의 전 과정을 경험합니다.",
          "pay": "100000",
          "period": "3개월",
          "participants": 2,
          "category": "풀스택"
        }
      ]
    }
  ],
  "mentorings": [
    {
      "mentoringId": 1,
      "mentorId": 1,
      "title": "Spring Boot 기초부터 실무까지",
      "content": "Spring Boot를 활용한 RESTful API 개발과 JPA, Security 등 실무에서 필요한 기술을 배웁니다.",
      "pay": "50000",
      "period": "1개월",
      "participants": 5,
      "category": "백엔드",
      "status": "active",
      "aboutMe": "10년차 백엔드 개발자입니다. 스타트업부터 대기업까지 다양한 환경에서 경험을 쌓았습니다.",
      "field": "백엔드",
      "task": "Spring Boot, MSA, DevOps",
      "mentorName": "김개발",
      "career": "시니어"
    },
    {
      "mentoringId": 2,
      "mentorId": 1,
      "title": "MSA 설계 및 구현",
      "content": "마이크로서비스 아키텍처의 개념부터 실제 구현까지 단계별로 학습합니다.",
      "pay": "80000",
      "period": "2개월",
      "participants": 3,
      "category": "아키텍처",
      "status": "active",
      "aboutMe": "10년차 백엔드 개발자입니다. 스타트업부터 대기업까지 다양한 환경에서 경험을 쌓았습니다.",
      "field": "백엔드",
      "task": "Spring Boot, MSA, DevOps",
      "mentorName": "김개발",
      "career": "시니어"
    },
    {
      "mentoringId": 3,
      "mentorId": 2,
      "title": "React + TypeScript 완벽 가이드",
      "content": "React와 TypeScript를 함께 사용하여 타입 안정성이 높은 애플리케이션을 개발하는 방법을 배웁니다.",
      "pay": "60000",
      "period": "1.5개월",
      "participants": 4,
      "category": "프론트엔드",
      "status": "active",
      "aboutMe": "5년차 프론트엔드 개발자입니다. React와 TypeScript를 주력으로 사용합니다.",
      "field": "프론트엔드",
      "task": "React, TypeScript, Next.js",
      "mentorName": "이프론트",
      "career": "미들"
    },
    {
      "mentoringId": 4,
      "mentorId": 3,
      "title": "풀스택 개발자 되기",
      "content": "프론트엔드부터 백엔드, 배포까지 웹 서비스 개발의 전 과정을 경험합니다.",
      "pay": "100000",
      "period": "3개월",
      "participants": 2,
      "category": "풀스택",
      "status": "active",
      "aboutMe": "8년차 풀스택 개발자입니다. 프론트부터 백엔드, 인프라까지 전반적인 멘토링이 가능합니다.",
      "field": "풀스택",
      "task": "Node.js, React, Docker, AWS",
      "mentorName": "박풀스택",
      "career": "시니어"
    },
    {
      "mentoringId": 5,
      "mentorId": 2,
      "title": "Next.js로 배우는 SSR/SSG",
      "content": "Next.js를 활용한 서버 사이드 렌더링과 정적 사이트 생성 방법을 배웁니다.",
      "pay": "70000",
      "period": "1개월",
      "participants": 3,
      "category": "프론트엔드",
      "status": "active",
      "aboutMe": "5년차 프론트엔드 개발자입니다. React와 TypeScript를 주력으로 사용합니다.",
      "field": "프론트엔드",
      "task": "React, TypeScript, Next.js",
      "mentorName": "이프론트",
      "career": "미들"
    },
    {
      "mentoringId": 6,
      "mentorId": 1,
      "title": "JPA 심화 과정",
      "content": "JPA의 고급 기능과 성능 최적화 방법을 실습을 통해 학습합니다.",
      "pay": "65000",
      "period": "1.5개월",
      "participants": 4,
      "category": "백엔드",
      "status": "active",
      "aboutMe": "10년차 백엔드 개발자입니다. 스타트업부터 대기업까지 다양한 환경에서 경험을 쌓았습니다.",
      "field": "백엔드",
      "task": "Spring Boot, MSA, DevOps",
      "mentorName": "김개발",
      "career": "시니어"
    },
    {
      "mentoringId": 7,
      "mentorId": 1,
      "title": "Docker & Kubernetes 실무",
      "content": "Docker 컨테이너화부터 Kubernetes 오케스트레이션까지 DevOps 필수 기술을 배웁니다.",
      "pay": "90000",
      "period": "2개월",
      "participants": 3,
      "category": "DevOps",
      "status": "active",
      "aboutMe": "10년차 백엔드 개발자입니다. 스타트업부터 대기업까지 다양한 환경에서 경험을 쌓았습니다.",
      "field": "백엔드",
      "task": "Spring Boot, MSA, DevOps",
      "mentorName": "김개발",
      "career": "시니어"
    },
    {
      "mentoringId": 8,
      "mentorId": 2,
      "title": "Vue.js 3 Composition API",
      "content": "Vue.js 3의 Composition API를 활용한 모던 프론트엔드 개발 방법론을 학습합니다.",
      "pay": "55000",
      "period": "1개월",
      "participants": 6,
      "category": "프론트엔드",
      "status": "active",
      "aboutMe": "5년차 프론트엔드 개발자입니다. React와 TypeScript를 주력으로 사용합니다.",
      "field": "프론트엔드",
      "task": "React, TypeScript, Next.js",
      "mentorName": "이프론트",
      "career": "미들"
    },
    {
      "mentoringId": 9,
      "mentorId": 3,
      "title": "AWS 클라우드 아키텍처",
      "content": "AWS 서비스를 활용한 클라우드 인프라 설계와 구축 방법을 기초부터 고급까지 학습합니다.",
      "pay": "120000",
      "period": "3개월",
      "participants": 4,
      "category": "DevOps",
      "status": "active",
      "aboutMe": "8년차 풀스택 개발자입니다. 프론트부터 백엔드, 인프라까지 전반적인 멘토링이 가능합니다.",
      "field": "풀스택",
      "task": "Node.js, React, Docker, AWS",
      "mentorName": "박풀스택",
      "career": "시니어"
    },
    {
      "mentoringId": 10,
      "mentorId": 1,
      "title": "Redis & 캐시 전략",
      "content": "Redis를 활용한 데이터 캐싱 전략과 성능 최적화 기법을 실습을 통해 학습합니다.",
      "pay": "75000",
      "period": "1.5개월",
      "participants": 5,
      "category": "백엔드",
      "status": "active",
      "aboutMe": "10년차 백엔드 개발자입니다. 스타트업부터 대기업까지 다양한 환경에서 경험을 쌓았습니다.",
      "field": "백엔드",
      "task": "Spring Boot, MSA, DevOps",
      "mentorName": "김개발",
      "career": "시니어"
    },
    {
      "mentoringId": 11,
      "mentorId": 2,
      "title": "React Native 모바일 앱 개발",
      "content": "React Native를 사용한 크로스 플랫폼 모바일 앱 개발을 기초부터 배포까지 학습합니다.",
      "pay": "85000",
      "period": "2개월",
      "participants": 4,
      "category": "모바일",
      "status": "active",
      "aboutMe": "5년차 프론트엔드 개발자입니다. React와 TypeScript를 주력으로 사용합니다.",
      "field": "프론트엔드",
      "task": "React, TypeScript, Next.js",
      "mentorName": "이프론트",
      "career": "미들"
    },
    {
      "mentoringId": 12,
      "mentorId": 3,
      "title": "GraphQL API 설계",
      "content": "GraphQL을 활용한 효율적인 API 설계와 구현 방법을 Apollo Server와 함께 학습합니다.",
      "pay": "95000",
      "period": "2개월",
      "participants": 3,
      "category": "백엔드",
      "status": "active",
      "aboutMe": "8년차 풀스택 개발자입니다. 프론트부터 백엔드, 인프라까지 전반적인 멘토링이 가능합니다.",
      "field": "풀스택",
      "task": "Node.js, React, Docker, AWS",
      "mentorName": "박풀스택",
      "career": "시니어"
    },
    {
      "mentoringId": 13,
      "mentorId": 1,
      "title": "Kafka & 이벤트 스트리밍",
      "content": "Apache Kafka를 활용한 이벤트 스트리밍 아키텍처와 실시간 데이터 처리 방법을 학습합니다.",
      "pay": "110000",
      "period": "2.5개월",
      "participants": 2,
      "category": "아키텍처",
      "status": "active",
      "aboutMe": "10년차 백엔드 개발자입니다. 스타트업부터 대기업까지 다양한 환경에서 경험을 쌓았습니다.",
      "field": "백엔드",
      "task": "Spring Boot, MSA, DevOps",
      "mentorName": "김개발",
      "career": "시니어"
    },
    {
      "mentoringId": 14,
      "mentorId": 2,
      "title": "Webpack & Vite 모던 번들링",
      "content": "Webpack과 Vite를 활용한 모던 프론트엔드 번들링 최적화 기법을 실습을 통해 학습합니다.",
      "pay": "65000",
      "period": "1개월",
      "participants": 5,
      "category": "프론트엔드",
      "status": "active",
      "aboutMe": "5년차 프론트엔드 개발자입니다. React와 TypeScript를 주력으로 사용합니다.",
      "field": "프론트엔드",
      "task": "React, TypeScript, Next.js",
      "mentorName": "이프론트",
      "career": "미들"
    },
    {
      "mentoringId": 15,
      "mentorId": 3,
      "title": "MongoDB & NoSQL 데이터베이스",
      "content": "MongoDB를 활용한 NoSQL 데이터베이스 설계와 최적화 기법을 실무 예제로 학습합니다.",
      "pay": "80000",
      "period": "1.5개월",
      "participants": 4,
      "category": "데이터베이스",
      "status": "active",
      "aboutMe": "8년차 풀스택 개발자입니다. 프론트부터 백엔드, 인프라까지 전반적인 멘토링이 가능합니다.",
      "field": "풀스택",
      "task": "Node.js, React, Docker, AWS",
      "mentorName": "박풀스택",
      "career": "시니어"
    },
    {
      "mentoringId": 16,
      "mentorId": 1,
      "title": "Python Django REST API",
      "content": "Django REST Framework를 활용한 RESTful API 개발과 인증/인가 시스템 구축을 학습합니다.",
      "pay": "70000",
      "period": "2개월",
      "participants": 6,
      "category": "백엔드",
      "status": "active",
      "aboutMe": "10년차 백엔드 개발자입니다. 스타트업부터 대기업까지 다양한 환경에서 경험을 쌓았습니다.",
      "field": "백엔드",
      "task": "Spring Boot, MSA, DevOps",
      "mentorName": "김개발",
      "career": "시니어"
    },
    {
      "mentoringId": 17,
      "mentorId": 2,
      "title": "Flutter 크로스 플랫폼",
      "content": "Flutter를 활용한 iOS/Android 동시 개발과 네이티브 기능 연동 방법을 학습합니다.",
      "pay": "90000",
      "period": "2.5개월",
      "participants": 3,
      "category": "모바일",
      "status": "active",
      "aboutMe": "5년차 프론트엔드 개발자입니다. React와 TypeScript를 주력으로 사용합니다.",
      "field": "프론트엔드",
      "task": "React, TypeScript, Next.js",
      "mentorName": "이프론트",
      "career": "미들"
    },
    {
      "mentoringId": 18,
      "mentorId": 3,
      "title": "Terraform 인프라 자동화",
      "content": "Terraform을 활용한 Infrastructure as Code 실습과 AWS 리소스 자동 프로비저닝을 학습합니다.",
      "pay": "100000",
      "period": "2개월",
      "participants": 4,
      "category": "DevOps",
      "status": "active",
      "aboutMe": "8년차 풀스택 개발자입니다. 프론트부터 백엔드, 인프라까지 전반적인 멘토링이 가능합니다.",
      "field": "풀스택",
      "task": "Node.js, React, Docker, AWS",
      "mentorName": "박풀스택",
      "career": "시니어"
    }
  ],
  "mentees": [
    {
      "menteeId": 1,
      "memberId": 1,
      "mentorName": "김개발",
      "mentoringId": 1,
      "message": "Spring Boot를 제대로 배우고 싶습니다!",
      "schedule": "주말 오후",
      "paymentKey": "test_payment_key_1",
      "email": "demo@example.com",
      "title": "Spring Boot 기초부터 실무까지",
      "content": "Spring Boot를 활용한 RESTful API 개발과 JPA, Security 등 실무에서 필요한 기술을 배웁니다.",
      "pay": "50000",
      "participants": 5,
      "category": "백엔드"
    }
  ],
  "payments": [
    {
      "id": 1,
      "memberId": 1,
      "mentoringId": 1,
      "amount": 50000,
      "paymentKey": "test_payment_key_1",
      "orderId": "order_123456",
      "status": "completed"
    }
  ]
};
