export const db = {
  members: [
    {
      id: 1,
      email: 'demo@example.com',
      password: 'password123',
      nickname: '데모유저',
      isLogin: false,
    },
    {
      id: 2,
      email: 'mentor@example.com',
      password: 'password123',
      nickname: '김멘토',
      isLogin: false,
    },
    {
      id: 3,
      email: 'mentee@example.com',
      password: 'password123',
      nickname: '이멘티',
      isLogin: false,
    },
  ],
  mentors: [
    {
      mentorId: 1,
      memberId: 1,
      company: '데모컴퍼니',
      department: '개발팀',
      position: '시니어 개발자',
      career: 10,
      field: ['IT', '소프트웨어'],
      task: ['백엔드', 'DevOps'],
      email: 'demo@example.com',
      phone: '010-1234-5678',
      nickname: '데모유저',
    },
    {
      mentorId: 2,
      memberId: 2,
      company: '네이버',
      department: '검색사업부',
      position: '프론트엔드 개발자',
      career: 5,
      field: ['IT', '웹'],
      task: ['프론트엔드'],
      email: 'mentor@example.com',
      phone: '010-1111-2222',
      nickname: '김멘토',
    },
  ],
  mentorings: [
    {
      mentoringId: 1,
      mentorId: 1,
      title: '데모유저의 멘토링',
      content: '커리어 고민, 기술 스택, 사이드 프로젝트 등 어떤 주제든 좋습니다.',
      startDate: '2024-01-01',
      endDate: '2024-12-31',
      numberOfPeople: 5,
      amount: 50000,
      category: 'IT',
      company: '데모컴퍼니',
      department: '개발팀',
      position: '시니어 개발자',
      career: 10,
      field: ['IT', '소프트웨어'],
      task: ['백엔드', 'DevOps'],
      email: 'demo@example.com',
      phone: '010-1234-5678',
      nickname: '데모유저',
    },
    {
      mentoringId: 2,
      mentorId: 2,
      title: '프론트엔드 개발자 취업 멘토링',
      content: '비전공자에서 네이버 프론트엔드 개발자가 되기까지의 경험을 공유합니다.',
      startDate: '2024-05-01',
      endDate: '2024-08-31',
      numberOfPeople: 10,
      amount: 100000,
      category: 'IT',
      company: '네이버',
      department: '검색사업부',
      position: '프론트엔드 개발자',
      career: 5,
      field: ['IT', '웹'],
      task: ['프론트엔드'],
      email: 'mentor@example.com',
      phone: '010-1111-2222',
      nickname: '김멘토',
    },
  ],
  mentees: [
     {
      menteeId: 1,
      memberId: 1,
      mentoringId: 2,
      message: '데모유저가 멘토링을 신청합니다.',
      schedule: '2024-07-15T10:00:00',
    },
    {
      menteeId: 2,
      memberId: 3,
      mentoringId: 2,
      message: '프론트엔드 개발자가 되고 싶습니다. 잘 부탁드립니다.',
      schedule: '2024-07-20T14:00:00',
    },
  ],
  payments: [],
};
